version: "3.9"

services:
  rakaiseto:
    image: ghcr.io/rakaiseto/rakaiseto.com:latest
    pull_policy: always
    networks:
      - rakaiseto-com-network
    container_name: rakaiseto-com
    restart: always
    ports:
      - "127.0.0.1:21001:80"

networks:
  rakaiseto-com-network:
